UrlShortener/Models/ErrorViewModel.cs
namespace UrlShortener.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UrlShortener/Models/UrlShortenerViewModel.cs
using System;

namespace UrlShortener.Models
{
    public class UrlShortenerViewModel
    {
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
    }
}

UrlShortener/Controllers/UrlShortenerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UrlShortener.Models;
using System.Diagnostics;
using UrlShortener.Dapper;
using System.Threading.Tasks;

namespace UrlShortener.Controllers
{
    public class UrlShortenerController : Controller
    {
        private readonly ILogger<UrlShortenerController> _logger;
        private IUrlRepository _urlRepository;


        public UrlShortenerController(ILogger<UrlShortenerController> logger, IUrlRepository urlRepository)
        {
            _urlRepository = urlRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //validateUrl
            //handleURLShortening
            //ReturnView
            return View("Index", new UrlShortenerViewModel { LongUrl = "", ShortUrl = "" });
        }

        [HttpPost]
        public async Task<ViewResult> Index(UrlShortenerViewModel urlshortener)
        {
            //validateUrl
            //handleURLShortening
            //ReturnView
            //var urlValidator = new UrlValidator();
            var shortenedUrl = await _urlRepository.CreateShortUrl(urlshortener.LongUrl);

            return View("Index", new UrlShortenerViewModel { LongUrl = urlshortener.LongUrl, ShortUrl = shortenedUrl });
        }

        [HttpGet]
        [Route("{shortUrl:regex([[a-z0-9]]$):maxlength(8)}")] //[[a-z]]//|[[0-9]]){{3,8}}
        public async Task<RedirectResult> RedirectShortUrl(string shortUrl)
        {
            var url = await _urlRepository.GetLongUrl(shortUrl.ToLower());
            return Redirect(url);
        }


        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UrlShortener/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Url Shortener</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="UrlShortener" asp-action="Index">UrlShortener</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UrlShortener" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UrlShortener" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Url Shortener - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UrlShortener/Views/UrlShortener/About.cshtml
@{
    ViewData["Title"] = "About";
}
<div class="container">
    <h2>Problem</h2>

    <p>Number of domains a base36 (8 character) alphanumeric a-z 0-9 string can represent</p>
    <p>
        Combinations possible in 8-character string:
        36*36*36*36*36*36*36*36 = 2,821,109,907,456
    </p>
    <p>
        Background:  366.8 million domains where in existence in 2020.
        The annual growth rate was 4.2 % - 15million
    </p>

    <h2>My design</h2>
    <p>
        <ul>
            <li>every shortened url is 8 characters long</li>
            <li>avoid duplicate short Urls</li>
            <li>allow duplicate long urls</li>
        </ul>
    </p>
    <p>
        Shortening problem:
        Tiny URL uses a string of length 8 lower case characters with each character in range of [a-z] or [0-9]
    </p>
    <p>
        36^8 - 366,000,000 = 2,820,743,907,456 domains left that can be represented in an 8 character string
    </p>
</div>

<div class="container">
    <ul>
        <li>Protocol http://, http://</li>
        <li>mid level domain e.g google</li>
        <li>slashes / path /</li>
        <li>top level domains .co.uk .com .org . edu</li>
        <li>file endings for resources .jpg, .pdf</li>
        <li>top level domains .co.uk .com .org . edu</li>
    </ul>
</div>

    <h2>Sample Urls minified by Tiny Url</h2>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>https://filmdaily.co/wp-content/uploads/2020/04/lede-cat-memes.jpghttps://filmdaily.co/wp-content/uploads/2020/04/lede-cat-memes.jpg</td>
            <td>https://tinyurl.com/2dvbw9b8</td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
    <tr>
        <th>Base10</th><th><b>Base36</b></th></tr></thead>
         <tbody><tr><td>100</td><td>2S</td></tr><tr><td>1000</td>
        <td>RS</td></tr><tr><td>10000</td><td>7PS</td></tr><tr>
        <td>100000</td><td>255S</td></tr><tr><td>1000000</td>
        <td>LFLS</td></tr><tr><td>1000000000</td><td>GJDGXS</td>
    </tr>
    </tbody>
</table>

UrlShortener/Views/UrlShortener/Index.cshtml
@model UrlShortenerViewModel

<div class="text-center">
</div>
<h1>Url Shortener</h1>
<form  method="post" asp-controller="UrlShortener" asp-action="index">
    <div class="mb-3">
    <label class="form-label" >Write your long url here</label>
    <input type="text" class="form-control longUrl-input-text" id="longUrl" data-val="true" value="@Model.LongUrl" asp-for="LongUrl" aria-describedby="longUrl">
    </div>
    <div class="mb-3">
        <label for="shortUrl" class="form-label">Your short Url</label>
        <input class="form-control longUrl-input-text" id="shortUrl" type="text" data-val="true" value="@Model.ShortUrl" asp-for="ShortUrl">
    </div>
    <button type="submit" class="btn btn-primary float-sm-left">Submit</button>
</form>